on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql_db: "my_db"
          postgresql_user: "test_user"
          postgresql_password: "test_password"

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL to be ready
        run: |
          counter=0
          max_attempts=300  
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for Postgres... attempt $((counter+1))"
            sleep 2
            counter=$((counter+1))
            if [ $counter -ge $max_attempts ]; then
              echo "Postgres did not become ready in time!"
              exit 1
            fi
          done

      - name: Run tests
        run: PGDATABASE=my_db PGUSER=test_user PGPASSWORD=test_password PGHOST=localhost npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy to Production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: $${{secrets.RENDER_SERVICE_ID}}
          api-key: $${{secrets.RENDER_API_KEY}}
